name: colorize_image
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #DI
  get_it: ^7.6.4


  #State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #Responsive
  responsive_framework: ^1.1.1

  #Image Picker
  image_picker: ^1.0.4

  #Others
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  fluttertoast: ^8.2.4
  dio:
  dotted_border: ^2.1.0
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/dubai/

  fonts:
    - family: dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
          weight: 400
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/dubai/Dubai-Bold.otf
          weight: 700